# Generated by Django 5.2.7 on 2025-11-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_kidsproduct_womensproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mens', 'Menswear'), ('womens', 'Womenswear'), ('kids', 'Kidswear')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='KidsProduct',
        ),
        migrations.DeleteModel(
            name='WomensProduct',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.DeleteModel(
            name='MensProduct',
        ),
    ]
